---
languageName: 英语
params:
  description: 为什么使用 Numpy？它有强大的高维数组、有数字计算工具、互可操作、高性能、开源。
  navbarlogo:
    image: logos/numpy.svg
    link: /
  hero:
    #Main hero title
    title: NumPy
    #Hero subtitle (optional)
    subtitle: 使用 Python 进行科学计算的基本包
    #Button text
    buttontext: 入门
    #Where the main hero button links to
    buttonlink: "/install"
    #Hero image (from static/images/___)
    image: logos/numpy.svg
  #Customizable navbar. For a dropdown, add a "sublinks" list.
  news:
    title: D&I Grant from CZI
    content: Including NumPy, SciPy, Matplotlib and Pandas
    url: /news
  shell:
    title: 占位符
    promptlabel: 交互式shell提示
    button:
      - 
        label: 启用交互式教程shell。
        text: 启用
  shellcontent:
    intro:
      - 
        title: 尝试使用NumPy
        text: 启用交互式教程shell。
    loading:
      - 
        title: 当我们等待时...
        text: 正在前往 mybinder.org 启动容器...
    docslink: 别忘了查看 <a href="https://numpy.org/doc/stable" target="_blank">用户手册</a>。
  casestudies:
    title: 案例研究
    features:
      - 
        title: 第一张黑洞图像
        text: NumPy 是怎么配合 SciPy 和 Matplotlib 等库来让事件视界望远镜（Eht）生成第一张黑洞图像的
        img: /images/content_images/case_studies/blackhole.png
        alttext: 这是黑洞的第一张图像。它是黑色背景上衬着的一个橙色圆环。
        url: /case-studies/blackhole-image
      - 
        title: 引力波探测
        text: 在1916年，阿尔伯特·爱因斯坦预测了引力波的存在。100年后，激光干涉引力波天文台（LIGO）的科学家利用 NumPy 证明了引力波的存在。
        img: /images/content_images/case_studies/gravitional.png
        alttext: 两个相互环绕的天体。它们改变了周围的引力。
        url: /case-studies/gw-discov
      - 
        title: 运动分析
        text: Cricket Analytics 正在通过统计模型和预测分析来改进队员的团队的表现，改变体育界。NumPy 让其中很多的分析成为了可能。
        img: /images/content_images/case_studies/sports.jpg
        alttext: 绿色的赛场上的板球。
        url: /case-studies/cricket-analytics
      - 
        title: 使用深度学习进行估计
        text: DeepLabCut 使用 NumPy 来加速进行涉及观察动物行为的科学研究，以便跨物种和时间尺度推动研究发展。
        img: /images/content_images/case_studies/deeplabcut.png
        alttext: 猎豹姿势分析
        url: /case-studies/deeplabcut-dnn
  keyfeatures:
    features:
      - 
        title: 强大的高维数组
        text: 快速、多面性、NumPy向量化、索引化和广播概念是当今数组计算的事实标准。
      - 
        title: 数字计算工具
        text: NumPy 提供了丰富全面的数学函数、随机数生成器、线性代数函数、傅式变换等等。
      - 
        title: 互操作性
        text: NumPy 支持范围广泛的硬件和计算平台，并且在分布式、GPU和稀疏数组库中也能得到很好的应用。
      - 
        title: 高性能
        text: NumPy 的核心是高度优化的 C 代码，同时兼顾了Python语言的灵活性和编译代码的高性能。
      - 
        title: 简单易用
        text: NumPy的高度模块化的语法使得任何背景或经验级别的程序员都能够快速上手。
      - 
        title: 开放源代码
        text: Distributed under a liberal [BSD license](https://github.com/numpy/numpy/blob/main/LICENSE.txt), NumPy is developed and maintained [publicly on GitHub](https://github.com/numpy/numpy) by a vibrant, responsive, and diverse [community](/community).
  tabs:
    title: 生态系统
  section5: false
navbar:
  - 
    title: 安装
    url: /install
  - 
    title: 文档
    url: https://numpy.org/doc/stable
  - 
    title: 学习指南
    url: /learn
  - 
    title: 社区
    url: /community
  - 
    title: 关于我们
    url: /about
  - 
    title: 参与贡献
    url: /contribute
footer:
  logo: numpy.svg
  socialmediatitle: ""
  socialmedia:
    - 
      link: https://github.com/numpy/numpy
      icon: github
    - 
      link: https://twitter.com/numpy_team
      icon: 推特
  quicklinks:
    column1:
      title: ""
      links:
        - 
          text: 安装
          link: /install
        - 
          text: 文档
          link: https://numpy.org/doc/stable
        - 
          text: 学习指南
          link: /learn
        - 
          text: 引用 NumPy
          link: /citing-numpy
        - 
          text: 版本规划
          link: https://numpy.org/neps/roadmap.html
    column2:
      links:
        - 
          text: 关于我们
          link: /about
        - 
          text: 社区
          link: /community
        - 
          text: User surveys
          link: /user-surveys
        - 
          text: Contribute
          link: /contribute
        - 
          text: Code of conduct
          link: /code-of-conduct
    column3:
      links:
        - 
          text: 获得帮助
          link: /gethelp
        - 
          text: 使用条款
          link: /terms
        - 
          text: 隐私政策
          link: /privacy
        - 
          text: 宣传材料
          link: /press-kit

